# 005文本大数据分析
文本数据是人类中重要的知识载体  
文本分析是将非结构化的原始文本

## LSI

In [1]:
import numpy as np

In [19]:
C=np.array([[1,0,1,0,0,0],[0,1,0,0,0,0],[1,1,0,0,0,0],[1,0,0,1,1,0],[0,0,0,1,0,1]])
U,s,VT=np.linalg.svd(C)

In [20]:
print(U.shape)
print(VT.shape)
print(s.shape)

(5, 5)
(6, 6)
(5,)


In [26]:
k=2
print(U[:,:k])
print(VT[:k,:])
print(s[:3])

[[ 0.44034748 -0.29617436]
 [ 0.12934635 -0.33145069]
 [ 0.47553026 -0.51111524]
 [ 0.70302032  0.35057241]
 [ 0.26267284  0.64674677]]
[[ 0.74862305  0.2797116   0.2036288   0.44656311  0.32509596  0.12146715]
 [-0.28645399 -0.52845914 -0.18576119  0.6255207   0.21987976  0.40564094]]
[2.16250096 1.59438237 1.27529025]


In [27]:
np.diag(s[:3])

array([[2.16250096, 0.        , 0.        ],
       [0.        , 1.59438237, 0.        ],
       [0.        , 0.        , 1.27529025]])

In [28]:
word=np.matmul(U[:,:k],np.diag(s[:k]))
print(word)

[[ 0.95225185 -0.47221518]
 [ 0.2797116  -0.52845914]
 [ 1.02833465 -0.81491313]
 [ 1.52028211  0.55894647]
 [ 0.56803026  1.03116165]]


In [30]:
np.matmul(np.diag(s[:k]),VT[:k,:])

array([[ 1.61889806,  0.60487661,  0.44034748,  0.96569316,  0.70302032,
         0.26267284],
       [-0.45671719, -0.84256593, -0.29617436,  0.99731918,  0.35057241,
         0.64674677]])

U/V的行是个特征向量

## 词袋子，词集，TF-IDF

In [31]:
s=[['我','是','中国','科学','院','大学','的','学生','专业','是','计算机','科学'],
   ['我','是','数据','科学','实验室','的','学生','研究','方向','是','计算机','科学'],
   ['计算机','是','科学','研究','中','的','重要','工具']]
voc=set()
for sen in s:
    for word in sen:
        voc.add(word)
print(voc)

{'计算机', '中', '学生', '工具', '方向', '数据', '我', '院', '实验室', '中国', '科学', '是', '的', '专业', '研究', '大学', '重要'}


In [34]:
dic={}
i=0
voc=list(voc)
for i,w in enumerate(voc):
    dic[w]=i
print(dic)
    

{'计算机': 0, '中': 1, '学生': 2, '工具': 3, '方向': 4, '数据': 5, '我': 6, '院': 7, '实验室': 8, '中国': 9, '科学': 10, '是': 11, '的': 12, '专业': 13, '研究': 14, '大学': 15, '重要': 16}


In [36]:
###词集合
s_set=[]
for sen in s:
    sen_set=[0]*len(dic)
    for w in sen:
        sen_set[dic[w]]=1
    s_set.append(sen_set)
print(s_set)

[[1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0], [1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0], [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1]]


In [37]:
####词袋子
s_bag=[]
for sen in s:
    sen_bag=[0]*len(dic)
    for w in sen:
        sen_bag[dic[w]]+=1
    s_bag.append(sen_bag)
print(s_bag)

[[1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2, 2, 1, 1, 0, 1, 0], [1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 2, 2, 1, 0, 1, 0, 0], [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1]]


In [38]:
###TF-IDF
doc_num=len(s)
print(doc_num)
for sen in s:
    sen_total_word=len(sen)##这篇文章中的单词总数

3


In [42]:
import numpy as np
word_bag=np.array(s_bag)
print(word_bag)
word_set=np.array(s_set)

[[1 0 1 0 0 0 1 1 0 1 2 2 1 1 0 1 0]
 [1 0 1 0 1 1 1 0 1 0 2 2 1 0 1 0 0]
 [1 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1]]


In [44]:
doc_count=np.sum(word_set,axis=0)##单词在几个文档中出现过
print(doc_count)

[3 1 2 1 1 1 2 1 1 1 3 3 3 1 2 1 1]


In [45]:
###逆文档频率 
IDF=np.log(doc_num/doc_count)
print(IDF)

[0.         1.09861229 0.40546511 1.09861229 1.09861229 1.09861229
 0.40546511 1.09861229 1.09861229 1.09861229 0.         0.
 0.         1.09861229 0.40546511 1.09861229 1.09861229]


In [48]:
###TF
word_total_per_doc=np.sum(word_bag,axis=1).reshape(3,1)
print(word_total_per_doc)

[[12]
 [12]
 [ 8]]


In [50]:
tf=word_bag/word_total_per_doc
print(tf)

[[0.08333333 0.         0.08333333 0.         0.         0.
  0.08333333 0.08333333 0.         0.08333333 0.16666667 0.16666667
  0.08333333 0.08333333 0.         0.08333333 0.        ]
 [0.08333333 0.         0.08333333 0.         0.08333333 0.08333333
  0.08333333 0.         0.08333333 0.         0.16666667 0.16666667
  0.08333333 0.         0.08333333 0.         0.        ]
 [0.125      0.125      0.         0.125      0.         0.
  0.         0.         0.         0.         0.125      0.125
  0.125      0.         0.125      0.         0.125     ]]


In [54]:
tf_idf=tf*IDF

In [55]:
print(tf_idf)

[[0.         0.         0.03378876 0.         0.         0.
  0.03378876 0.09155102 0.         0.09155102 0.         0.
  0.         0.09155102 0.         0.09155102 0.        ]
 [0.         0.         0.03378876 0.         0.09155102 0.09155102
  0.03378876 0.         0.09155102 0.         0.         0.
  0.         0.         0.03378876 0.         0.        ]
 [0.         0.13732654 0.         0.13732654 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.05068314 0.         0.13732654]]
